name: test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out PyPackage
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev_requirements.txt

      - name: Run mypy
        run: mypy pypackage

      - name: Run flake8
        run: flake8 .

      - name: Run black
        run: black --check --diff pypackage

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]

    steps:
      - name: Check out PyPackage
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev_requirements.txt
      - name: Run unit tests.
        run: pytest pypackage
      - name: Submit coverage report to Codecov.
        if: ${{ matrix.python-version == 3.8 }}
        uses: codecov/codecov-action@v2.0.3
        with:
          fail_ci_if_error: true
